/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./inertia/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./inertia/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./inertia/components/ui/alert/AlertTitle.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Checkbox: typeof import('./inertia/components/ui/checkbox/Checkbox.vue')['default']
    Command: typeof import('./inertia/components/ui/command/Command.vue')['default']
    CommandDialog: typeof import('./inertia/components/ui/command/CommandDialog.vue')['default']
    CommandEmpty: typeof import('./inertia/components/ui/command/CommandEmpty.vue')['default']
    CommandGroup: typeof import('./inertia/components/ui/command/CommandGroup.vue')['default']
    CommandInput: typeof import('./inertia/components/ui/command/CommandInput.vue')['default']
    CommandItem: typeof import('./inertia/components/ui/command/CommandItem.vue')['default']
    CommandList: typeof import('./inertia/components/ui/command/CommandList.vue')['default']
    CommandSeparator: typeof import('./inertia/components/ui/command/CommandSeparator.vue')['default']
    CommandShortcut: typeof import('./inertia/components/ui/command/CommandShortcut.vue')['default']
    Dialog: typeof import('./inertia/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./inertia/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./inertia/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./inertia/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./inertia/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./inertia/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./inertia/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./inertia/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./inertia/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./inertia/components/ui/dialog/DialogTrigger.vue')['default']
    FirmInput: typeof import('./inertia/components/FormInput.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormInput: typeof import('./inertia/components/FormInput.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    GlobalCommand: typeof import('./inertia/components/GlobalCommand.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Timeline: typeof import('./inertia/components/Timeline.vue')['default']
  }
}
