/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    FuckTimeline: typeof import('./inertia/components/fuckTimeline.vue')['default']
    Timeline: typeof import('./inertia/components/Timeline.vue')['default']
    TTimeline: typeof import('./inertia/components/tTimeline.vue')['default']
  }
}
